### ISSUE TITLE
Incompatible with Cypress 11 

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/cy2-azure#2]
Cypress 11 has a different packaging and does not expose the source files. As a result - cy2-azure is not working anymore. 

There are also complains about Cypress 10 compatibility: https://sorry-cypress.slack.com/archives/C01346MRQBY/p1669814106853329

**Comment by DamienCassou** [comment]
We are unable to update Cypress because of this :-(.

**Comment by kuldea-paulo** [comment]
We are also unable to upgrade from 9.7.0. 
We use azure blob storage to store the screenshots when the tests fail. 
The error we are having, as soon as we use `cy2-azure`, is
```
Error: ENOENT: no such file or directory, copyfile '/root/.cache/Cypress/12.0.0/Cypress/resources/app/packages/server/config/app.yml' -> '/root/.cache/Cypress/12.0.0/Cypress/resources/app/packages/server/config/_app.yml'
    at Object.copyFileSync (node:fs:2817:3)
    at Object.<anonymous> (/e2e/node_modules/cy2-azure/dist/patch.js:57:25)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/e2e/node_modules/cy2-azure/dist/patch.js:15:28)
    at _next (/e2e/node_modules/cy2-azure/dist/patch.js:33:17) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/root/.cache/Cypress/12.0.0/Cypress/resources/app/packages/server/config/app.yml',
  dest: '/root/.cache/Cypress/12.0.0/Cypress/resources/app/packages/server/config/_app.yml'
```

**Comment by agoldis** [comment]
Most chances you will have to switch to [cypress-cloud](https://currents.notion.site/Cypress-12-and-Currents-Sorry-Cypress-3f9f29285f9242c78b0ba63cf9225c6c) package
